---
- name: Uninstall a webserver
  hosts: web
  become: true
  tasks:
    - name: Ensure nginx is stopped and disabled
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Ensure nginx is Uninstalled
      ansible.builtin.package:
        name: nginx
        state: absent