---
- hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present
    
    - name: Ensure PyMySQL is installed.
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present

    - name: Ensure MariaDB service is started and enabled.
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create database webappdb.
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    
    - name: Create user webappuser with privileges on webappdb.
      community.mysql.mysql_user:
       name: webappuser
       password: secretpassword
       priv: '*.*:ALL'
       state: present
       login_unix_socket: /var/lib/mysql/mysql.sock