---
- name: Install a webserver
  hosts: web
  become: true
  tasks:
    - name: Ensure nginx is installed
      become: true
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure nginx is started at boot
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true